### ISSUE TITLE
New scraping failure in Otsar

### ISSUE THREAD

**Issue by hcosteff** [eshaham/israeli-bank-scrapers#471] opened 2020-06-27 17:06 UTC
can anyone help me debug this?

```Run task scrapers
scraping Bank Otsar Hahayal
Bank Otsar Hahayal: START_SCRAPING
Bank Otsar Hahayal: INITIALIZING
Bank Otsar Hahayal: LOGGING_IN
Bank Otsar Hahayal: LOGIN_SUCCESS
Bank Otsar Hahayal: TERMINATING
Bank Otsar Hahayal: END_SCRAPING
success: false
error type: GENERIC
error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
Error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at <anonymous>
(node:29) UnhandledPromiseRejectionWarning: Error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at <anonymous>
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled 
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by esakal** [comment] 2020-07-18 22:40
Hi @hcosteff 
I don't have access to Otsar account so I can only provide general directions:
1. in the scraper options, set `showBrowser: true,`. it should now show you a browser when scraping 
2. run the scraper, make sure that you are reaching the same page that you get by logging into the system manually.
3. this selector is used also if you have multiple pages. if it does try to navigate to another page, please respond if you see there a list of transactions.

**Comment by eshaham** [comment] 2020-08-19 05:22
perhaps @matanelgabsi can help?

**Comment by matanelgabsi** [comment] 2020-08-19 06:11
I've checked now - and there is no error for me..
maybe this is due to not having any transactions.. I will try to check
@hcosteff does that makes sense?

**Comment by matanelgabsi** [comment] 2020-08-19 06:17
I can confirm that the scraper works fine when there is no data, so that is not the issue
also looked at the code:
await waitUntilElementFound(page, 'table#dataTable077, #NO_DATA077');
seems that this was taken under consideration.. @hcosteff is it possible this is just a network error? if not - I'll be glad if you can try to give some more info, or try to scrape other dates and tell us if that helps..

**Comment by esakal** [comment] 2020-08-19 09:19
I'm closing this ticket for now, @hcosteff feel free to re-open it if it still happens

**Closed by esakal** 2020-08-19 09:19 UTC
Labels: bug

**Comment by hcosteff** [comment] 2020-08-20 08:03
Yea sorry, I didn't update, this issue happened to me for several days and then stopped completely (I didn't change or redeploy or anything).

My guess is that the changed the DOM and then reverted it, but I'm not sure.

Thanks for looking into it and sorry again 🙇‍♂️
