### ISSUE TITLE
VisaCal timeout issue

### ISSUE THREAD

**Issue by roisec** [eshaham/israeli-bank-scrapers#766] opened 2023-04-01 12:07 UTC
Hi, 
I have an issue with Visacal scraping in the last week,
The error message: TIMEOUT - wait for iframe with login form.

**Comment by roisec** [comment] 2023-04-02 06:38
I guess it's the same issue as https://github.com/eshaham/israeli-bank-scrapers/issues/763

**Comment by baruchiro** [comment] 2023-04-03 06:45
@eshaham duplicate of #763

**Closed** 2023-04-08 12:40 UTC
