### ISSUE TITLE
Mizrahi Tefahot scraping brainstorming

### ISSUE THREAD

**Issue by tounano** [eshaham/israeli-bank-scrapers#74] opened 2018-02-14 10:52 UTC
Hi,

I've tried to reverse engineer scraping of Mizrahi.

They work with the stupid dot net session thing.

Couldn't find a way to do proper scraping. Anyone here tried to scrape them?

**Comment by eshaham** [comment] 2018-02-15 08:18
@tounano I don't have an account in Mizrahi Tefahot, so I didn't tried scraping them.
But I'm not sure why you can't simply go the headless browser route. Under the browser, you don't need to take care of the session, it is done for you by the browser.
Some of the scrapers, like the one for Discount bank, even get access to simple REST calls, after logging in within the browser.

**Comment by tounano** [comment] 2018-02-15 08:45
@eshaham Nice. That was my second option.

They don't have REST API.

I'll try to imitate what you did with discount.

**Comment by eshaham** [comment] 2018-02-25 20:41
@tounano let me know if we still need this issue, or we can close it.

**Comment by arikfr** [comment] 2018-03-06 18:38
@tounano another option is to see what their mobile app does. It might be using a saner API. Just configure some proxy on your phone and see what happens.

**Comment by tamirtw** [comment] 2018-03-25 11:54
Just tried iPhone + Charles (With SSL cert installed).
Seems like they have certificate pinning, thus making difficult to intercept the calls, maybe
if you have an older version of the app.
Like @eshaham said, headless browser (like the discount scraper) seems like the way to go here. 
Btw, same applies to Fibi (Massad,First international bank,U-Bank use the same infra). They sign request bodies which makes a lot harder going the direct REST approach

**Comment by esakal** [comment] 2018-10-05 06:51
Hi @tounano, Did you have any luck with scraping Mizrahi? I saw your comments about headless browser which might work here. But I think it is easier working with puppeteer as we did in some scrapers. You can extend [BaseScraperWithBrowser](https://github.com/eshaham/israeli-bank-scrapers/blob/a48216996fe7e5f6a314cc4f01017261170fb7c1/src/scrapers/base-scraper-with-browser.js) and use [Leumi](https://github.com/eshaham/israeli-bank-scrapers/blob/a48216996fe7e5f6a314cc4f01017261170fb7c1/src/scrapers/leumi.js) or [Leumi card](https://github.com/eshaham/israeli-bank-scrapers/blob/a48216996fe7e5f6a314cc4f01017261170fb7c1/src/scrapers/leumi-card.js) as a reference.

btw, if you are working with an IDE like webstorm or others that allow node.js debugging, using the [library playground built-in support](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#using-the-playground) might be very useful

It would be great adding Mizrahi to the library, let me know if you have further questions.

**Comment by baruchiro** [comment] 2019-08-12 04:42
OK, I've started working on it now.

This is my first time with NodeJS, but I think I'll get it. I looked at the other scrapers.

Tips are welcome.

**Comment by esakal** [comment] 2019-08-12 05:56
Well learning/coping from other scrapers are the best way to do it. 

1. Since my previous comment a year ago we switched from playground to unit tests. 
2. To make sure you bootstrap everything correctly I suggest you to search the term `hapoalim`(if IDE allow it search complete word with match case). Then just copy things and do the same for `mizrachi` 
![image](https://user-images.githubusercontent.com/4751797/62847324-4b15eb00-bcde-11e9-95b3-5eb90e6f8bd9.png)
3. You need to decide first if you need to use puppeteer or not. If Mizrachi exposes an API that is accessible directly you should use that strategy (inherit from `BaseScraper`), otherwise use puppeteer (inherit from `BaseScraperWithBrowser`). 

Enjoy

**Comment by baruchiro** [comment] 2019-08-12 07:23
1. Sure, I copied the tests from `leumi` and I working to pass them.
 2. 👍
 3. It seems that we expecting for an API, according to [this](https://www.mizrahi-tefahot.co.il/Lists/BankMizrahiSiteAssets/Reports/20001184e.pdf) document:
 
 ![image](https://user-images.githubusercontent.com/17686879/62850311-270cd680-bceb-11e9-9b48-8cb74226ca7b.png)

**Comment by esakal** [comment] 2019-08-12 14:14
great!

regarding 1st suggestion, i meant in other places as well like `.tests-config.tpl.js` and `definitions.js`.... it might be easier to review those places and add `mizrachi` in the same way.

![image](https://user-images.githubusercontent.com/4751797/62871592-702d4c80-bd24-11e9-919b-220be3f5c362.png)

**Comment by baruchiro** [comment] 2019-08-29 14:26
During my work on the Mizrahi scraper, I came across an API request that the site performs to retrieve all transactions.
The problem is that the request must to send a **secret key** in the `header`.

I haven't checked much, but the key seems to come from an object being initialized in **Angular**.
In addition, the key goes inside the header of the requests the site sends.

So do you know a way to access an instance of an object in **Angular**, or record a **request** that the site makes?
With one of these ways, I can get the **secret key** and retrieve all the transactions.
Otherwise, I'll have to read HTML with paging.

**Comment by esakal** [comment] 2019-08-30 10:34
when the institute is using Angular, ASP.net, react and other libraries that manages state between calls, you should inherit `base-scraper-with-browser.js` and then as long as you are using the same puppeteer page to both login and scrape content, puppeteer should take care of passing header secrets. Following your other PRs I assume you already inherit from this class? if so, you can create a draft PR with your progress so I will be able to refer to your actual implementation.

**Comment by baruchiro** [comment] 2019-08-30 15:34
I will try to explain the situation better, there may be tips from another direction.

Of course, I inherit from `BaseScraperWithBrowser`, and I've already done some scraping steps (login, for example).
After login, I came across 2 options:
 1. Go to a **legacy address** where there is the HTML inside the `iframe`. (From #177 )
**Advantages:** The HTML is old and simple, has an `id` for most elements and no special tricks.
**Disadvantage:** I had problems with the `iframe`.
 2. Scratch the **regular site**.
**Disadvantages:** The `css selectors` of the elements include the hierarchy, because there is no `id`s. The elements are powered by `Angular` so it is sometimes difficult to control them directly but it is necessary to simulate a user.

------

Now, I am currently trying out the **regular site**. To retrieve data within a specific range (e.g. 7 months), enter dates and click "_Submit_". The site then displays a table of the data.
The problem is that **the data comes in pages**.
Up to 50 rows per page. So to get them all I have to take the first 50, then move on to the next page, etc.

But I saw that when you click "_Submit_", the site sends an `ajax` (I think) request to the server to get all the data.
I want to send this request, but for that, I need to attach a **unique session ID**.
I think about 2 options:
 1. The **unique identifier** is obtained by an object that appears in `Angular` code. Is there a way to access this object?
 2. The site uses the **unique identifier** to check that the session is valid every few seconds. Do I have a way to record one of these requests and get the information out of it?

----

I don't think sharing the code will help at this point. But I'll share.

**Comment by esakal** [comment] 2019-08-31 19:14
Thank you for your detailed explanation. I know better understand what you try to achieve and it is better then just reviewing the code.

*legacy address* did you try using the same page instance you logged in with to access the iframe url directly (unless they have post messages or direct calls to `top` it should work).

If not, I do think `puppeteer` is natural choice for SPA (Angular, React) and you can easily handle pagination with puppeteer (see how we did it in the past for [leumi-card](https://github.com/eshaham/israeli-bank-scrapers/blob/01792304b8de0a66548410863fa4a16bbb1f8c07/src/scrapers/leumi-card.js#L228)). regarding the css selectors this is indeed annoying but feasible. I think it complicated developing most of the scrapers that are puppeteer based, but once done it just works and I don't remember many issues opened as a result of frequent css selector changes.  Please review the link attached above [leumi-card](https://github.com/eshaham/israeli-bank-scrapers/blob/01792304b8de0a66548410863fa4a16bbb1f8c07/src/scrapers/leumi-card.js#L228) and let me know if one of my suggestions helped or you want to discuss about possible alternatives

**Comment by baruchiro** [comment] 2019-09-01 08:40
> **legacy address** did you try using the same page instance you logged in with to access the iframe url directly (unless they have post messages or direct calls to `top` it should work).

If I access directly to the `iframe` URL, I got an empty page, probably a request is missing. (I don't know what is the `top` you mentioned)

----

I will take the paging option for now. Thanks.

**Comment by baruchiro** [comment] 2019-09-04 11:53
> 2. The site uses the **unique identifier** to check that the session is valid every few seconds. Do I have a way to record one of these requests and get the information out of it?

I found it, and it is very simple!

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforrequesturlorpredicate-options

**Closed** 2019-11-02 22:23 UTC
Labels: question
